// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:39:25
// Original: shift_reg.v
// Vulnerability: T4
// Model: gpt-4o
// Version: 3
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module shift_reg(
    input clk, rst, shift_in,
    output reg [7:0] data_out
);

always @(posedge clk or posedge rst) begin
    if (rst)
        data_out <= 8'b0;
    else
        data_out <= {data_out[6:0], shift_in};
end

// trojan_insertion_begin
// Added vulnerability region to increase power consumption

// A continuously toggling register that doesn't affect data_out
reg [7:0] toggle_reg; 
always @(posedge clk or posedge rst) begin
    if (rst) 
        toggle_reg <= 8'b0;
    else 
        toggle_reg <= ~toggle_reg; // Continuously toggles to increase switching activity
end
// trojan_insertion_end

endmodule