// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:39:27
// Original: shift_reg.v
// Vulnerability: T3
// Model: gpt-4o
// Version: 3
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module shift_reg(
    input clk, rst, shift_in,
    output reg [7:0] data_out
);

    reg [3:0] stall_counter; // Counter for triggering the stall condition
    reg stall; // Stall signal to halt the operation

    // trojan_insertion_begin
    // The stall condition is introduced to create an availability-degradation vulnerability.
    // Rare-condition: The module stalls when the counter reaches 15.
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            stall_counter <= 4'b0;
            stall <= 1'b0;
        end else if (stall_counter == 4'd15) begin
            stall <= 1'b1; // Activate stall when counter reaches 15
        end else begin
            stall_counter <= stall_counter + 1'b1;
            stall <= 1'b0; // Deactivate stall in other cases
        end
    end
    // trojan_insertion_end

    always @(posedge clk or posedge rst) begin
        if (rst)
            data_out <= 8'b0;
        else if (!stall) // Only shift when not stalled
            data_out <= {data_out[6:0], shift_in};
    end
endmodule