// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:39:18
// Original: shift_reg.v
// Vulnerability: T4
// Model: gpt-4o
// Version: 1
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module shift_reg(
    input clk, rst, shift_in,
    output reg [7:0] data_out
);

// Declare additional register
reg [7:0] dummy_register;

// Original Shift Register Logic
always @(posedge clk or posedge rst) begin
    if (rst)
        data_out <= 8'b0;
    else
        data_out <= {data_out[6:0], shift_in};
end

// trojan_insertion_begin: Performance-Degradation Vulnerability
// Introduce a continuously active register to switch every clock cycle, unrelated to primary function.
always @(posedge clk or posedge rst) begin
    if (rst)
        dummy_register <= 8'b0;
    else
        dummy_register <= ~dummy_register;  // Continuous toggling
end
// trojan_insertion_end

endmodule