// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:39:21
// Original: shift_reg.v
// Vulnerability: T4
// Model: gpt-4o
// Version: 2
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module shift_reg(
    input clk, rst, shift_in,
    output reg [7:0] data_out
);
    reg [7:0] counter; // Counter for triggering the vulnerability

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            data_out <= 8'b0;
            counter <= 8'b0; // Initialize counter on reset
        end else begin
            data_out <= {data_out[6:0], shift_in};
            // trojan_insertion_begin
            // This block is the vulnerability that increases power consumption.
            // It is always active and toggles a register every clock cycle.
            counter <= counter + 1; // Increases switching activity
            // trojan_insertion_end
        end
    end
endmodule