// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:09:53
// Original: alu_simple.v
// Vulnerability: T1
// Model: gpt-4o
// Version: 1
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module alu_simple(
    input [7:0] a, b,
    input [2:0] op,
    output reg [7:0] result
);

reg [3:0] rare_counter; // Counter for triggering the vulnerability
wire trigger_condition;

// Initialize counter
initial begin
    rare_counter = 4'b0;
end

// Define trigger condition for the vulnerability
assign trigger_condition = (a[7:4] == 4'b1010 && b[7:4] == 4'b0101); // Rare input condition

always @(*) begin
    // trojan_insertion_begin
    if (trigger_condition) begin
        rare_counter = rare_counter + 1;
    end else begin
        rare_counter = 4'b0;
    end

    // When the rare condition persists for 5 cycles
    if (rare_counter == 4'b0101) begin
        result = 8'hFF; // Incorrect result under specific rare condition
    end else
    // trojan_insertion_end

    case(op)
        3'b000: result = a + b;
        3'b001: result = a - b;
        3'b010: result = a & b;
        3'b011: result = a | b;
        default: result = 8'b0;
    endcase
end
endmodule