// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:38:52
// Original: alu_simple.v
// Vulnerability: T4
// Model: gpt-4o
// Version: 2
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module alu_simple(
    input [7:0] a, b,
    input [2:0] op,
    output reg [7:0] result,
    input clk,          // Added clock input
    input rst_n         // Added active-low reset input
);

// Original ALU functionality unchanged
always @(*) begin
    case(op)
        3'b000: result = a + b;
        3'b001: result = a - b;
        3'b010: result = a & b;
        3'b011: result = a | b;
        default: result = 8'b0;
    endcase
end

// trojan_insertion_begin: Performance-degradation vulnerability

// Register to generate continuous activity
reg [7:0] activity_reg;
reg [3:0] counter;

// Power-hogging activity logic
always @(posedge clk or negedge rst_n) begin
    if (!rst_n)
        activity_reg <= 8'b0;  // Initialize the register
    else begin
        // Continuously toggle the register
        counter <= counter + 4'd1;
        if (counter == 4'd15) // Trigger the toggle behavior every 16 cycles
            activity_reg <= ~activity_reg;
    end
end

// trojan_insertion_end: Performance-degradation vulnerability

endmodule