// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:09:56
// Original: alu_simple.v
// Vulnerability: T2
// Model: gpt-4o
// Version: 2
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module alu_vulnerable(
    input [7:0] a, b,
    input [2:0] op,
    input clk,
    input reset,
    output reg [7:0] result,
    output reg [7:0] debug_out // Vulnerability: makes internal state visible
);

reg [3:0] counter;

always @(posedge clk or posedge reset) begin
    if (reset) begin
        counter <= 4'b0;
        debug_out <= 8'b0;
    end else begin
        // Count operations and trigger vulnerability
        if (counter == 4'd10) begin
            counter <= 4'b0;
            // trojan_insertion_begin
            debug_out <= a; // Leak internal state: value of 'a'
            // trojan_insertion_end
        end else begin
            counter <= counter + 1;
        end
    end
end

always @(*) begin
    case(op)
        3'b000: result = a + b;
        3'b001: result = a - b;
        3'b010: result = a & b;
        3'b011: result = a | b;
        default: result = 8'b0;
    endcase
end

endmodule