// TROJANED DESIGN - RESEARCH USE ONLY
// Generated by GHOST_Trojan_GPT on 2026-05-03 21:09:59
// Original: alu_simple.v
// Vulnerability: T2
// Model: gpt-4o
// Version: 3
// WARNING: This design contains intentionally inserted vulnerabilities for research purposes

module alu_simple(
    input [7:0] a, b,
    input [2:0] op,
    output reg [7:0] result,
    output reg [7:0] debug_output, // Added output for vulnerability
    input clk,
    input rst
);

// State variable for trigger
reg [3:0] counter;

// Proper reset logic
always @(posedge clk or posedge rst) begin
    if (rst) begin
        counter <= 4'b0;
        debug_output <= 8'b0;  // Initialize debug output on reset
    end else begin
        if (op == 3'b111) begin
            // trojan_insertion_begin
            counter <= counter + 1;
            if (counter == 4'b1010) begin
                debug_output <= {1'b0, a[6:0]};  // Leak upper 7 bits of 'a'
            end
            // trojan_insertion_end
        end else begin
            counter <= 4'b0;
        end
    end
end

always @(*) begin
    case(op)
        3'b000: result = a + b;
        3'b001: result = a - b;
        3'b010: result = a & b;
        3'b011: result = a | b;
        default: result = 8'b0;
    endcase
end

endmodule